title: "CS 4476-A Fall 2025"
instructor: "Judy Hoffman"
instructor_url: "https://jhoffman.github.io/"

permalink: pretty

ed_discussion: "https://edstem.org/us/courses/80676"
canvas: "https://gatech.instructure.com/courses/460854"
gradescope: "https://www.gradescope.com/courses/1061439"
staff_mailing: "cs4476-fall2025@groups.gatech.edu"

